language: python
cache: pip
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - WAGTAIL='>=1.8,<1.9'
  - WAGTAIL='>=1.9,<1.10'

services:
  - postgresql

addons:
  postgresql: "9.2"

before_script:
  - psql -c 'create database wagtail_pgsearchbackend;' -U postgres

install:
  - pip install six  # Build sometimes error out because six cannot be found
  - pip install wagtail$WAGTAIL
  - pip install -e . -r requirements-dev.txt

script:
  make test
